pipeline {
agent { label 'slave' }

```
environment {
    AWS_REGION = 'ap-south-1'
    ACCOUNT_ID = '475790160792'

    IMAGE_NAME = 'web'
    IMAGE_TAG = "${BUILD_NUMBER}"

    ECR_DEV  = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/web-dev"
    ECR_PROD = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/web-prod"

    HELM_REPO = 'https://github.com/snehaCodes276/application-helm-charts.git'
}

stages {

    stage('Clean') {
        steps { cleanWs() }
    }

    stage('Checkout') {
        steps { checkout scm }
    }

    stage('Install Dependencies') {
        steps {
            dir('web') {
                sh 'npm install || true'
            }
        }
    }

    stage('Static Analysis') {
        parallel {

            stage('Sonar') {
                steps {
                    dir('web') {
                        withSonarQubeEnv('sonarqube') {
                            sh 'sonar-scanner -Dsonar.projectKey=web -Dsonar.sources=. || true'
                        }
                    }
                }
            }

            stage('OWASP') {
                steps {
                    dir('web') {
                        sh '/opt/dependency-check/bin/dependency-check.sh --project web --scan . --out . || true'
                    }
                }
            }
        }
    }

    stage('Quality Gate') {
        steps {
            script {
                try {
                    waitForQualityGate abortPipeline: false
                } catch (e) {
                    echo "Skipping QG"
                }
            }
        }
    }

    stage('Tests') {
        steps {
            dir('web') {
                sh 'npm test || true'
            }
        }
    }

    stage('Docker Build') {
        steps {
            dir('web') {
                sh '''
                echo "Building Docker Image..."
                ls -la
                docker build -t ${IMAGE_NAME}:${IMAGE_TAG} . || exit 1
                '''
            }
        }
    }

    stage('Security Scan Image') {
        steps {
            sh 'grype ${IMAGE_NAME}:${IMAGE_TAG} || true'
        }
    }

    stage('Push to ECR') {
        steps {
            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']]) {
                sh '''
                aws ecr get-login-password --region ${AWS_REGION} | \
                docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

                REPO=${ECR_DEV}
                [ "$BRANCH_NAME" = "master" ] && REPO=${ECR_PROD}

                docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${REPO}:${IMAGE_TAG}
                docker push ${REPO}:${IMAGE_TAG}
                '''
            }
        }
    }

    stage('Helm Lint') {
        steps {
            sh '''
            rm -rf charts
            git clone ${HELM_REPO}
            kube-linter lint application-helm-charts/application-helm-charts/web || true
            '''
        }
    }

    stage('Check EKS') {
        steps {
            sh 'kubectl get nodes'
        }
    }
}
```

}
